language: node_js
node_js:
- '6'
services:
- mongodb
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  slack:
    secure: uhuyLLD5rr7dGwnzsnXBSZrH2RDECJBQ+jO/5na7ghpQp2mksZoBrURSBcXvePI/9YomaLShNzJuMohVmKK2MQcnWSvWNWz/VQTdkyiVRCywWT/199VVlLFhe6gavKkBnp6g1SuUA0yGMmMTn4h5kJEoeiD5+BPR6GsqJfbb9Ug1/miNcODSiT3XJqZ3tnFQbkPi6gF3bcZzcQBRdfI4uJitcadKaUxpqLNaT/JIbI1RoUxoi9x9hmTm3vDkL8LvcTK0MskoGiePcAIn9JjkkbM87PI70qDIXWKBJvDrfn+2zA3ehigDqojajZKyrv+P0lS9FPt8VbKpJv5z/vKqbDdYkjWN8ODWcrpbjS6Hm5ogX+ySOiIksvO6rYyCIuppnljY0XpoXSWqoBaloN07E69YERBiUUYxRVZaRp3Pw5mSn0oa+LHDgqu/HMa0GXc+XGj2ZBtQxHkELD0qfhr4RfdGo0MElDx7AwkGumdiJtNDROs7ZQe3hsbrLKk4omd0CA6o9ebZ8T21CGrXCAv2s16og+IkLolyHKRa050lzIrxhzI/5CFAR6u9FYsfPEo/mroiTpb7v+4d8AugZt3vpYCWJeWZLKdTxGBuoLRPYVcEf1Kvkekm3dP+Zql9pxSxsmuGwI+Y2nGUzAJ9sZf3RfllioQEd+b+cvSna1mj9Do=
deploy:
  provider: heroku
  api_key:
    secure: guR033sS5Tc+BFCM/DUm/DWOv5YTb+KF96QVfhbANST5/mc7d798O1j1v8WjgCNNlTMYZ+LLiUMpxYwIkatn9YfsLygjvQKiX/n7OqxFX62zY4Bmi9PWF1ojVIZOJnUAEYi2Bw19aRLA/5rWXdE+3JbnW/QKttko2Jc1E3Fk7Cb0grj0JT09rJiHn+oq7Gsult6F94fHIhwR3LN6MwIjP9w5hv3cvz850R8FdH/i5lj2OLAK825lrpD+2BQoil3ryUhzruS6B4ghoWg2m0BMdrByg3BwcHbs1DGhOl6RpSNQf56CfN60j6riiUk+1T11f3ZPRgky1FEhdA9BvnchENpsTNac10r+UxQuUtXO7DQLypoEk5hQ5ljTpwKkm7vuYpscHZz72KrUyKdLqP1wg57MHEGwrB7tJONAVjMMm0ken9cBFPuYZotOw9Kuvv1dLdskeTfnu0JgNKFhCTuV8PEge7N+mJdrpzOasx1j91t483X6r1Gr/e7qs3UNTXzO724w0tnPrbG6x8TJJsS3S/8O9KUr8iSPhH8R1qf1q9NcYjmXpLuQj5u6ZoIBecokEwrowlH2QbMOEqQRGYqPM2lSxlY+tqFoDEWInzEYCYrPcz84UwFZkjiioILx2zIhD4Z2efeDcFu2lCjFsUSe2m9VhE7Ao1AlWBxUI/6tK9Y=
